apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000        # Kubernetes service port
      targetPort: 5000  # Container port in Pod
      nodePort: 30500   # Exposed port for access from outside (for Minikube)
  type: NodePort