apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack:latest
        ports:
        - containerPort: 4566  
        env:
        - name: MONGODB_URI
          value: mongodb://localhost:27017/todos
        - name: S3_BUCKET_NAME
          value: mysamplebucket
        - name: S3_ENDPOINT_URL
          value: "http://localhost:4566"
        - name: AWS_REGION
          value: "ap-south-1"