apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  selector:
    app: localstack
  ports:
    - name: main
      protocol: TCP
      port: 4566
      targetPort: 4566
      nodePort: 30566   # Exposed port for external access
    - name: edge
      protocol: TCP
      port: 4571
      targetPort: 4571
      nodePort: 30571
  type: NodePort
